# settings
use_hardware:   False
time_delta:     0.75

#                 Agent ID, Init position, Take-off height
agent_init:     [['CF1', [0.5, 0.5, 0.4], 0.4],
                 ['CF2', [0, 0.5, 0.4], 0.4],
                 ['CF3', [-0.5, 0.5, 0.4], 0.4]]


agent_colors:   ['DarkBlue', 'DarkSlateGrey', 'MediumPurple']

#                 Pick ID, [pick x, pick y, pick z]
pick_loc:       [['P1', [0.5, 0.5, 0.4]],
                 ['P2', [0, 0.5, 0.4]],
                 ['P3', [-0.5, 0.5, 0.4]]]

#                 Drop ID, [drop x, drop y, drop z]
drop_loc:       [['D1', [0, -0.5]], 
                 ['D2', [0, -0.5]],
                 ['D3', [0, -0.5]]]

map:
  dimensions:
    x_max: 21
    x_min: -9
    y_max: 11
    y_min: -9
  obstacles:
  - !!python/tuple
    - 12
    - 6