# settings
use_hardware:   False
time_delta:     0.75

#                 Agent ID, Init position, Take-off height
agent_init:     [['CF1', [0.4572, 0.4572, 0.0], 0.4],
                 ['CF2', [0.4572, 1.9812, 0.0], 0.4],
                 ['CF3', [0.4572, 3.2004, 0.0], 0.4],
                 ['CF4', [0.4572, 4.7244, 0.0], 0.4]]


agent_colors:   ['DarkBlue', 'DarkSlateGrey', 'MediumPurple']

#                 Pick ID, [pick x, pick y, pick z]
pick_loc:       [['P1', [1.6764, 1.6764, 0.4]],
                 ['P2', [1.6764, 2.286, 0.4]], 
                 ['P3', [1.6764, 2.5908, 0.4]], 
                 ['P4', [1.6764, 3.2004, 0.4]],
                 ['P5', [1.6764, 3.81, 0.4]],
                 ['P6', [5.9436, 3.81, 0.4]],
                 ['P7', [5.9436, 3.2004, 0.4]],
                 ['P8', [5.9436, 2.5908, 0.4]],
                 ['P9', [5.9436, 2.286, 0.4]],
                 ['P10', [5.9436, 2.5908, 0.4]],
                 ['P11', [3.81, 1.6764, 0.4]],
                 ['P12', [3.81, 2.286, 0.4]],
                 ['P13', [3.81, 2.5908, 0.4]],
                 ['P14', [3.81, 3.2004, 0.4]],
                 ['P15', [3.81, 3.81, 0.4]]]

#                 Drop ID, [drop x, drop y, drop z]
drop_loc:       [['D1', [5.9436, 4.7244]], 
                 ['D2', [5.9436, 0.4572]]]

map:
  dimensions:
    x_max: 7.0104
    x_min: 0
    y_max: 5.4864
    y_min: 0
  obstacles:
  - !!python/list
    - !!python/tuple
      - 0
      - -6
    - !!python/tuple
      - 12
      - -3
  - !!python/list
    - !!python/tuple
      - 0
      - 3
    - !!python/tuple
      - 12
      - 6
  
  # - !!python/tuple
  #   - 0
  #   - -3
  # - !!python/tuple
  #   - 0
  #   - -3
  # - !!python/tuple
  #   - 0
  #   - -4
  # - !!python/tuple
  #   - 0
  #   - -5
  # - !!python/tuple
  #   - 0
  #   - -6
  # - !!python/tuple
  #   - 1
  #   - -3
  # - !!python/tuple
  #   - 1
  #   - -4
  # - !!python/tuple
  #   - 1
  #   - -5
  # - !!python/tuple
  #   - 1
  #   - -6
  # - !!python/tuple
  #   - 2
  #   - -3
  # - !!python/tuple
  #   - 2
  #   - -4
  # - !!python/tuple
  #   - 2
  #   - -5
  # - !!python/tuple
  #   - 2
  #   - -6
  # - !!python/tuple
  #   - 3
  #   - -3
  # - !!python/tuple
  #   - 3
  #   - -4
  # - !!python/tuple
  #   - 3
  #   - -5
  # - !!python/tuple
  #   - 3
  #   - -6
  # - !!python/tuple
  #   - 4
  #   - -3
  # - !!python/tuple
  #   - 4
  #   - -4
  # - !!python/tuple
  #   - 4
  #   - -5
  # - !!python/tuple
  #   - 4
  #   - -6
  # - !!python/tuple
  #   - 5
  #   - -3
  # - !!python/tuple
  #   - 5
  #   - -4
  # - !!python/tuple
  #   - 5
  #   - -5
  # - !!python/tuple
  #   - 5
  #   - -6
  # - !!python/tuple
  #   - 6
  #   - -3
  # - !!python/tuple
  #   - 6
  #   - -4
  # - !!python/tuple
  #   - 6
  #   - -5
  # - !!python/tuple
  #   - 6
  #   - -6
  # - !!python/tuple
  #   - 7
  #   - -3
  # - !!python/tuple
  #   - 7
  #   - -4
  # - !!python/tuple
  #   - 7
  #   - -5
  # - !!python/tuple
  #   - 7
  #   - -6
  # - !!python/tuple
  #   - 8
  #   - -3
  # - !!python/tuple
  #   - 8
  #   - -4
  # - !!python/tuple
  #   - 8
  #   - -5
  # - !!python/tuple
  #   - 8
  #   - -6
  # - !!python/tuple
  #   - 9
  #   - -3
  # - !!python/tuple
  #   - 9
  #   - -4
  # - !!python/tuple
  #   - 9
  #   - -5
  # - !!python/tuple
  #   - 9
  #   - -6
  # - !!python/tuple
  #   - 10
  #   - -3
  # - !!python/tuple
  #   - 10
  #   - -4
  # - !!python/tuple
  #   - 10
  #   - -5
  # - !!python/tuple
  #   - 10
  #   - -6
  # - !!python/tuple
  #   - 11
  #   - -3
  # - !!python/tuple
  #   - 11
  #   - -4
  # - !!python/tuple
  #   - 11
  #   - -5
  # - !!python/tuple
  #   - 11
  #   - -6
  # - !!python/tuple
  #   - 12
  #   - -3
  # - !!python/tuple
  #   - 12
  #   - -4
  # - !!python/tuple
  #   - 12
  #   - -5
  # - !!python/tuple
  #   - 12
  #   - -6
  # - !!python/tuple
  #   - 0
  #   - 3
  # - !!python/tuple
  #   - 0
  #   - 4
  # - !!python/tuple
  #   - 0
  #   - 5
  # - !!python/tuple
  #   - 0
  #   - 6
  # - !!python/tuple
  #   - 1
  #   - 3
  # - !!python/tuple
  #   - 1
  #   - 4
  # - !!python/tuple
  #   - 1
  #   - 5
  # - !!python/tuple
  #   - 1
  #   - 6
  # - !!python/tuple
  #   - 2
  #   - 3
  # - !!python/tuple
  #   - 2
  #   - 4
  # - !!python/tuple
  #   - 2
  #   - 5
  # - !!python/tuple
  #   - 2
  #   - 6
  # - !!python/tuple
  #   - 3
  #   - 3
  # - !!python/tuple
  #   - 3
  #   - 4
  # - !!python/tuple
  #   - 3
  #   - 5
  # - !!python/tuple
  #   - 3
  #   - 6
  # - !!python/tuple
  #   - 4
  #   - 3
  # - !!python/tuple
  #   - 4
  #   - 4
  # - !!python/tuple
  #   - 4
  #   - 5
  # - !!python/tuple
  #   - 4
  #   - 6
  # - !!python/tuple
  #   - 5
  #   - 3
  # - !!python/tuple
  #   - 5
  #   - 4
  # - !!python/tuple
  #   - 5
  #   - 5
  # - !!python/tuple
  #   - 5
  #   - 6
  # - !!python/tuple
  #   - 6
  #   - 3
  # - !!python/tuple
  #   - 6
  #   - 4
  # - !!python/tuple
  #   - 6
  #   - 5
  # - !!python/tuple
  #   - 6
  #   - 6
  # - !!python/tuple
  #   - 7
  #   - 3
  # - !!python/tuple
  #   - 7
  #   - 4
  # - !!python/tuple
  #   - 7
  #   - 5
  # - !!python/tuple
  #   - 7
  #   - 6
  # - !!python/tuple
  #   - 8
  #   - 3
  # - !!python/tuple
  #   - 8
  #   - 4
  # - !!python/tuple
  #   - 8
  #   - 5
  # - !!python/tuple
  #   - 8
  #   - 6
  # - !!python/tuple
  #   - 9
  #   - 3
  # - !!python/tuple
  #   - 9
  #   - 4
  # - !!python/tuple
  #   - 9
  #   - 5
  # - !!python/tuple
  #   - 9
  #   - 6
  # - !!python/tuple
  #   - 10
  #   - 3
  # - !!python/tuple
  #   - 10
  #   - 4
  # - !!python/tuple
  #   - 10
  #   - 5
  # - !!python/tuple
  #   - 10
  #   - 6
  # - !!python/tuple
  #   - 11
  #   - 3
  # - !!python/tuple
  #   - 11
  #   - 4
  # - !!python/tuple
  #   - 11
  #   - 5
  # - !!python/tuple
  #   - 11
  #   - 6
  # - !!python/tuple
  #   - 12
  #   - 3
  # - !!python/tuple
  #   - 12
  #   - 4
  # - !!python/tuple
  #   - 12
  #   - 5
  # - !!python/tuple
  #   - 12
  #   - 6