# This file assignes a task for each quadrotor. It starts from asking for start point, 
# then point at which item has to be picked up from and finally the location at which
# it has to be dropped off. It sets up each specific scenario!
# settings
use_hardware:   False
time_delta:     0.75

# Take off positions for each drone 
#                 Agent ID, Init position, Take-off height
agent_init:     [['CF1', [6.5, 0.46, 0.0], 0.4],
                 ['CF2', [6.5, 2, 0.0], 0.4],
                 ['CF3', [6.5, 3.5, 0.0], 0.4],
                 ['CF4', [6.5, 4.7, 0.0], 0.4]]


agent_colors:   ['DarkBlue', 'DarkSlateGrey', 'MediumPurple', 'SafetyOrange']

# Pick up location (the bin at which the item has to be picked
#                 Pick ID, [pick x, pick y, pick z] tbd 
pick_loc:       [['B5', [3.2, 3.8, 0.4]],
                 ['A7', [1.1, 2.3, 0.4]],
                 ['B1', [3.2, 1.7, 0.4]],
                 ['A5', [1.1, 3.2, 0.4]]]

node_loc:       [['A1', [5.3, 4.7, 0.4]],
                 ['A2', [3.2, 4.7, 0.4]], 
                 ['A3', [1.1, 4.7, 0.4]], 
                 ['A4', [1.1, 3.8, 0.4]], 
                 ['A5', [1.1, 3.2, 0.4]],
                 ['A6', [1.1, 2.6, 0.4]],
                 ['A7', [1.1, 2.3, 0.4]],
                 ['A8', [1.1, 1.7, 0.4]],
                 ['A9', [1.1, 0.5, 0.4]],
                 ['A10', [3.2, 0.5, 0.4]],
                 ['B1', [3.2, 1.7, 0.4]],
                 ['B2', [3.2, 2.3, 0.4]],
                 ['B3', [3.2, 2.6, 0.4]],
                 ['B4', [3.2, 3.2, 0.4]],
                 ['B5', [3.2, 3.8, 0.4]],
                 ['A11', [5.3, 0.5, 0.4]],
                 ['A12', [5.3, 1.7, 0.4]],
                 ['A13', [5.3, 2.3, 0.4]],
                 ['A14', [5.3, 2.6, 0.4]], 
                 ['A15', [5.3, 3.2, 0.4]], 
                 ['A16', [5.3, 3.8, 0.4]], 
                 ['S1', [6.5, 4.6, 0.4]], 
                 ['S2', [6.5, 2.0, 0.4]],
                 ['S3', [6.5, 3.5, 0.4]],
                 ['S4', [6.5, 4.7, 0.4]]]

#Drop off bin location has to be specified for each drone (hence the repetitions)
#                 Drop ID, [drop x, drop y, drop z]
drop_loc:       [['D1', [1.1, 4.7]], 
                 ['D2', [1.1, 0.5]],
                 ['D1', [1.1, 4.7]], 
                 ['D2', [1.1, 0.5]]]

map:
  dimensions:
    x_max: 70
    x_min: 0
    y_max: 55
    y_min: 0

  obstacles:
  - !!python/list
    - !!python/tuple
      - 15
      - 14
    - !!python/tuple
      - 26
      - 40
  - !!python/list
    - !!python/tuple
      - 38
      - 14
    - !!python/tuple
      - 49
      - 40
  bins: 
  - !!python/list 
    - !!python/tuple
      - 3
      - 3
    - !!python/tuple
      - 9
      - 9 
  - !!python/list
    - !!python/tuple
      - 3
      - 46
    - !!python/tuple
      - 9
      - 52
  bases: 
  - !!python/list 
    - !!python/tuple
      - 58
      - 0
    - !!python/tuple
      - 58
      - 12
  - !!python/list 
    - !!python/tuple
      - 58
      - 12
    - !!python/tuple
      - 70
      - 12

  - !!python/list 
    - !!python/tuple
      - 70
      - 14
    - !!python/tuple
      - 58
      - 14
  - !!python/list 
    - !!python/tuple
      - 58
      - 14
    - !!python/tuple
      - 58
      - 26
  - !!python/list 
    - !!python/tuple
      - 58
      - 26
    - !!python/tuple
      - 70
      - 26

  - !!python/list 
    - !!python/tuple
      - 70
      - 28
    - !!python/tuple
      - 58
      - 28
  - !!python/list 
    - !!python/tuple
      - 58
      - 28
    - !!python/tuple
      - 58
      - 41
  - !!python/list 
    - !!python/tuple
      - 58
      - 41
    - !!python/tuple
      - 70
      - 41

  - !!python/list 
    - !!python/tuple
      - 70
      - 43
    - !!python/tuple
      - 58
      - 43
  - !!python/list 
    - !!python/tuple
      - 58
      - 43
    - !!python/tuple
      - 58
      - 55
  - !!python/list 
    - !!python/tuple
      - 58
      - 55
    - !!python/tuple
      - 70
      - 55


  
  
  # - !!python/tuple
  #   - 0
  #   - -3
  # - !!python/tuple
  #   - 0
  #   - -3
  # - !!python/tuple
  #   - 0
  #   - -4
  # - !!python/tuple
  #   - 0
  #   - -5
  # - !!python/tuple
  #   - 0
  #   - -6
  # - !!python/tuple
  #   - 1
  #   - -3
  # - !!python/tuple
  #   - 1
  #   - -4
  # - !!python/tuple
  #   - 1
  #   - -5
  # - !!python/tuple
  #   - 1
  #   - -6
  # - !!python/tuple
  #   - 2
  #   - -3
  # - !!python/tuple
  #   - 2
  #   - -4
  # - !!python/tuple
  #   - 2
  #   - -5
  # - !!python/tuple
  #   - 2
  #   - -6
  # - !!python/tuple
  #   - 3
  #   - -3
  # - !!python/tuple
  #   - 3
  #   - -4
  # - !!python/tuple
  #   - 3
  #   - -5
  # - !!python/tuple
  #   - 3
  #   - -6
  # - !!python/tuple
  #   - 4
  #   - -3
  # - !!python/tuple
  #   - 4
  #   - -4
  # - !!python/tuple
  #   - 4
  #   - -5
  # - !!python/tuple
  #   - 4
  #   - -6
  # - !!python/tuple
  #   - 5
  #   - -3
  # - !!python/tuple
  #   - 5
  #   - -4
  # - !!python/tuple
  #   - 5
  #   - -5
  # - !!python/tuple
  #   - 5
  #   - -6
  # - !!python/tuple
  #   - 6
  #   - -3
  # - !!python/tuple
  #   - 6
  #   - -4
  # - !!python/tuple
  #   - 6
  #   - -5
  # - !!python/tuple
  #   - 6
  #   - -6
  # - !!python/tuple
  #   - 7
  #   - -3
  # - !!python/tuple
  #   - 7
  #   - -4
  # - !!python/tuple
  #   - 7
  #   - -5
  # - !!python/tuple
  #   - 7
  #   - -6
  # - !!python/tuple
  #   - 8
  #   - -3
  # - !!python/tuple
  #   - 8
  #   - -4
  # - !!python/tuple
  #   - 8
  #   - -5
  # - !!python/tuple
  #   - 8
  #   - -6
  # - !!python/tuple
  #   - 9
  #   - -3
  # - !!python/tuple
  #   - 9
  #   - -4
  # - !!python/tuple
  #   - 9
  #   - -5
  # - !!python/tuple
  #   - 9
  #   - -6
  # - !!python/tuple
  #   - 10
  #   - -3
  # - !!python/tuple
  #   - 10
  #   - -4
  # - !!python/tuple
  #   - 10
  #   - -5
  # - !!python/tuple
  #   - 10
  #   - -6
  # - !!python/tuple
  #   - 11
  #   - -3
  # - !!python/tuple
  #   - 11
  #   - -4
  # - !!python/tuple
  #   - 11
  #   - -5
  # - !!python/tuple
  #   - 11
  #   - -6
  # - !!python/tuple
  #   - 12
  #   - -3
  # - !!python/tuple
  #   - 12
  #   - -4
  # - !!python/tuple
  #   - 12
  #   - -5
  # - !!python/tuple
  #   - 12
  #   - -6
  # - !!python/tuple
  #   - 0
  #   - 3
  # - !!python/tuple
  #   - 0
  #   - 4
  # - !!python/tuple
  #   - 0
  #   - 5
  # - !!python/tuple
  #   - 0
  #   - 6
  # - !!python/tuple
  #   - 1
  #   - 3
  # - !!python/tuple
  #   - 1
  #   - 4
  # - !!python/tuple
  #   - 1
  #   - 5
  # - !!python/tuple
  #   - 1
  #   - 6
  # - !!python/tuple
  #   - 2
  #   - 3
  # - !!python/tuple
  #   - 2
  #   - 4
  # - !!python/tuple
  #   - 2
  #   - 5
  # - !!python/tuple
  #   - 2
  #   - 6
  # - !!python/tuple
  #   - 3
  #   - 3
  # - !!python/tuple
  #   - 3
  #   - 4
  # - !!python/tuple
  #   - 3
  #   - 5
  # - !!python/tuple
  #   - 3
  #   - 6
  # - !!python/tuple
  #   - 4
  #   - 3
  # - !!python/tuple
  #   - 4
  #   - 4
  # - !!python/tuple
  #   - 4
  #   - 5
  # - !!python/tuple
  #   - 4
  #   - 6
  # - !!python/tuple
  #   - 5
  #   - 3
  # - !!python/tuple
  #   - 5
  #   - 4
  # - !!python/tuple
  #   - 5
  #   - 5
  # - !!python/tuple
  #   - 5
  #   - 6
  # - !!python/tuple
  #   - 6
  #   - 3
  # - !!python/tuple
  #   - 6
  #   - 4
  # - !!python/tuple
  #   - 6
  #   - 5
  # - !!python/tuple
  #   - 6
  #   - 6
  # - !!python/tuple
  #   - 7
  #   - 3
  # - !!python/tuple
  #   - 7
  #   - 4
  # - !!python/tuple
  #   - 7
  #   - 5
  # - !!python/tuple
  #   - 7
  #   - 6
  # - !!python/tuple
  #   - 8
  #   - 3
  # - !!python/tuple
  #   - 8
  #   - 4
  # - !!python/tuple
  #   - 8
  #   - 5
  # - !!python/tuple
  #   - 8
  #   - 6
  # - !!python/tuple
  #   - 9
  #   - 3
  # - !!python/tuple
  #   - 9
  #   - 4
  # - !!python/tuple
  #   - 9
  #   - 5
  # - !!python/tuple
  #   - 9
  #   - 6
  # - !!python/tuple
  #   - 10
  #   - 3
  # - !!python/tuple
  #   - 10
  #   - 4
  # - !!python/tuple
  #   - 10
  #   - 5
  # - !!python/tuple
  #   - 10
  #   - 6
  # - !!python/tuple
  #   - 11
  #   - 3
  # - !!python/tuple
  #   - 11
  #   - 4
  # - !!python/tuple
  #   - 11
  #   - 5
  # - !!python/tuple
  #   - 11
  #   - 6
  # - !!python/tuple
  #   - 12
  #   - 3
  # - !!python/tuple
  #   - 12
  #   - 4
  # - !!python/tuple
  #   - 12
  #   - 5
  # - !!python/tuple
  #   - 12
  #   - 6