# This file assignes a task for each quadrotor. It starts from asking for start point, 
# then point at which item has to be picked up from and finally the location at which
# it has to be dropped off. It sets up each specific scenario!
# settings
use_hardware:   False
time_delta:     0.75

# Take off positions for each drone 
#                 Agent ID, Init position, Take-off height
agent_init:     [['HB1', [6.5, 0.7, 0.4], 0.4], 
                ['HB2', [6.5, 2.1, 0.4], 0.4],
                ['HB3', [6.5, 3.4, 0.4], 0.4],
                ['HB4', [6.5, 4.8, 0.4], 0.4]]


agent_colors:   ['DarkBlue', 'DarkSlateGrey', 'MediumPurple', 'SafetyOrange']

# Pick up location (the bin at which the item has to be picked
#                 Pick ID, [pick x, pick y, pick z] tbd 
pick_loc:       [['A6', [0.9, 3.9, 0.4]],
                 ['A8', [0.9, 1.6, 0.4]],
                 ['A8', [0.9, 1.6, 0.4]],
                 ['B3', [3.2, 3.9, 0.4]]]
                #  ['B1', [3.2, 1.6, 0.4]]]


#Drop off bin location has to be specified for each drone (hence the repetitions)
#                 Drop ID, [drop x, drop y, drop z]
drop_loc:       [['D1', [0.9, 5.0]], 
                 ['D2', [0.9, 0.5]],
                 ['D2', [0.9, 0.5]], 
                 ['D1', [0.9, 5.0]]]

map:
  dimensions:
    x_max: 70
    x_min: 0
    y_max: 55
    y_min: 0

  #TODO: Add description...
  nodes:       [['A1', [5.5, 5.0, 0.4], ['A2', 'S4']],
                ['A2', [4.3, 5.0, 0.4], ['A3']], 
                ['A3', [3.2, 5.0, 0.4], ['A4']], 
                ['A4', [2.1, 5.0, 0.4], ['A5']], 
                ['A5', [0.9, 5.0, 0.4], ['A6']],
                ['A6', [0.9, 3.9, 0.4], ['A7']],
                ['A7', [0.9, 2.7, 0.4], ['A8']],
                ['A8', [0.9, 1.6, 0.4], ['A9']],
                ['A9', [0.9, 0.5, 0.4], ['A10']],
                ['A10', [2.1, 0.5, 0.4], ['A11']],
                ['B1', [3.2, 1.6, 0.4], ['B2']],
                ['B2', [3.2, 2.7, 0.4], ['B3']],
                ['B3', [3.2, 3.9, 0.4], ['A3']],
                ['A11', [3.2, 0.5, 0.4], ['A12', 'B1']],
                ['A12', [4.3, 0.5, 0.4], ['A13']],
                ['A13', [5.5, 0.5, 0.4], ['A14', 'S1']],
                ['A14', [5.5, 1.6, 0.4], ['A15', 'S2']], 
                ['A15', [5.5, 2.7, 0.4], ['A16']], 
                ['A16', [5.5, 3.9, 0.4], ['A1', 'S3']], 
                ['S1', [6.5, 0.7, 0.4], ['A13']], 
                ['S2', [6.5, 2.1, 0.4], ['A14']],
                ['S3', [6.5, 3.4, 0.4], ['A16']],
                ['S4', [6.5, 4.8, 0.4], ['A1']]]
                  
  obstacles:
  - !!python/list
    - !!python/tuple
      - 15
      - 14
    - !!python/tuple
      - 26
      - 40
  - !!python/list
    - !!python/tuple
      - 38
      - 14
    - !!python/tuple
      - 49
      - 40
  bins: 
  - !!python/list 
    - !!python/tuple
      - 2
      - 2
    - !!python/tuple
      - 8
      - 8 
  - !!python/list
    - !!python/tuple
      - 2
      - 47
    - !!python/tuple
      - 8
      - 53
  bases: 
  - !!python/list 
    - !!python/tuple
      - 58
      - 0
    - !!python/tuple
      - 58
      - 12
  - !!python/list 
    - !!python/tuple
      - 58
      - 12
    - !!python/tuple
      - 70
      - 12

  - !!python/list 
    - !!python/tuple
      - 70
      - 14
    - !!python/tuple
      - 58
      - 14
  - !!python/list 
    - !!python/tuple
      - 58
      - 14
    - !!python/tuple
      - 58
      - 26
  - !!python/list 
    - !!python/tuple
      - 58
      - 26
    - !!python/tuple
      - 70
      - 26

  - !!python/list 
    - !!python/tuple
      - 70
      - 28
    - !!python/tuple
      - 58
      - 28
  - !!python/list 
    - !!python/tuple
      - 58
      - 28
    - !!python/tuple
      - 58
      - 41
  - !!python/list 
    - !!python/tuple
      - 58
      - 41
    - !!python/tuple
      - 70
      - 41

  - !!python/list 
    - !!python/tuple
      - 70
      - 43
    - !!python/tuple
      - 58
      - 43
  - !!python/list 
    - !!python/tuple
      - 58
      - 43
    - !!python/tuple
      - 58
      - 55
  - !!python/list 
    - !!python/tuple
      - 58
      - 55
    - !!python/tuple
      - 70
      - 55
