# settings
use_hardware:   False
time_delta:     0.75

# test with 2 drones and 2 drop points in a diamond, meant to show perpendicular collision
# at a pick point and drone responses

#                 Agent ID, Init position, Take-off height
agent_init:     [['CF1', [.1, 0.0 , 0.0], 0.4],
                 ['CF2', [0.5, -0.4, 0.0], 0.4],
                ]


agent_colors:   ['DarkBlue', 'DarkSlateGrey', 'MediumPurple']

#                 Pick ID, [pick x, pick y, pick z]
pick_loc:       [['P1', [0.5, 0, 0.4]],
                 ['P2', [0.5, 0, 0.4]], 
 ]

#                 Drop ID, [drop x, drop y, drop z]
drop_loc:       [['D1', [.5, 0.3]], 
                 ['D2', [.8, -0.0]], ]

map:
  dimensions:
    x_max: 21
    x_min: -9
    y_max: 11
    y_min: -9
  obstacles:
  - !!python/list
    - !!python/tuple
      - 0
      - -10
    - !!python/tuple
      - 12
      - -6
  - !!python/list
    - !!python/tuple
      - 0
      - 10
    - !!python/tuple
      - 12
      - 6
  
  # - !!python/tuple
  #   - 0
  #   - -3
  # - !!python/tuple
  #   - 0
  #   - -3
  # - !!python/tuple
  #   - 0
  #   - -4
  # - !!python/tuple
  #   - 0
  #   - -5
  # - !!python/tuple
  #   - 0
  #   - -6
  # - !!python/tuple
  #   - 1
  #   - -3
  # - !!python/tuple
  #   - 1
  #   - -4
  # - !!python/tuple
  #   - 1
  #   - -5
  # - !!python/tuple
  #   - 1
  #   - -6
  # - !!python/tuple
  #   - 2
  #   - -3
  # - !!python/tuple
  #   - 2
  #   - -4
  # - !!python/tuple
  #   - 2
  #   - -5
  # - !!python/tuple
  #   - 2
  #   - -6
  # - !!python/tuple
  #   - 3
  #   - -3
  # - !!python/tuple
  #   - 3
  #   - -4
  # - !!python/tuple
  #   - 3
  #   - -5
  # - !!python/tuple
  #   - 3
  #   - -6
  # - !!python/tuple
  #   - 4
  #   - -3
  # - !!python/tuple
  #   - 4
  #   - -4
  # - !!python/tuple
  #   - 4
  #   - -5
  # - !!python/tuple
  #   - 4
  #   - -6
  # - !!python/tuple
  #   - 5
  #   - -3
  # - !!python/tuple
  #   - 5
  #   - -4
  # - !!python/tuple
  #   - 5
  #   - -5
  # - !!python/tuple
  #   - 5
  #   - -6
  # - !!python/tuple
  #   - 6
  #   - -3
  # - !!python/tuple
  #   - 6
  #   - -4
  # - !!python/tuple
  #   - 6
  #   - -5
  # - !!python/tuple
  #   - 6
  #   - -6
  # - !!python/tuple
  #   - 7
  #   - -3
  # - !!python/tuple
  #   - 7
  #   - -4
  # - !!python/tuple
  #   - 7
  #   - -5
  # - !!python/tuple
  #   - 7
  #   - -6
  # - !!python/tuple
  #   - 8
  #   - -3
  # - !!python/tuple
  #   - 8
  #   - -4
  # - !!python/tuple
  #   - 8
  #   - -5
  # - !!python/tuple
  #   - 8
  #   - -6
  # - !!python/tuple
  #   - 9
  #   - -3
  # - !!python/tuple
  #   - 9
  #   - -4
  # - !!python/tuple
  #   - 9
  #   - -5
  # - !!python/tuple
  #   - 9
  #   - -6
  # - !!python/tuple
  #   - 10
  #   - -3
  # - !!python/tuple
  #   - 10
  #   - -4
  # - !!python/tuple
  #   - 10
  #   - -5
  # - !!python/tuple
  #   - 10
  #   - -6
  # - !!python/tuple
  #   - 11
  #   - -3
  # - !!python/tuple
  #   - 11
  #   - -4
  # - !!python/tuple
  #   - 11
  #   - -5
  # - !!python/tuple
  #   - 11
  #   - -6
  # - !!python/tuple
  #   - 12
  #   - -3
  # - !!python/tuple
  #   - 12
  #   - -4
  # - !!python/tuple
  #   - 12
  #   - -5
  # - !!python/tuple
  #   - 12
  #   - -6
  # - !!python/tuple
  #   - 0
  #   - 3
  # - !!python/tuple
  #   - 0
  #   - 4
  # - !!python/tuple
  #   - 0
  #   - 5
  # - !!python/tuple
  #   - 0
  #   - 6
  # - !!python/tuple
  #   - 1
  #   - 3
  # - !!python/tuple
  #   - 1
  #   - 4
  # - !!python/tuple
  #   - 1
  #   - 5
  # - !!python/tuple
  #   - 1
  #   - 6
  # - !!python/tuple
  #   - 2
  #   - 3
  # - !!python/tuple
  #   - 2
  #   - 4
  # - !!python/tuple
  #   - 2
  #   - 5
  # - !!python/tuple
  #   - 2
  #   - 6
  # - !!python/tuple
  #   - 3
  #   - 3
  # - !!python/tuple
  #   - 3
  #   - 4
  # - !!python/tuple
  #   - 3
  #   - 5
  # - !!python/tuple
  #   - 3
  #   - 6
  # - !!python/tuple
  #   - 4
  #   - 3
  # - !!python/tuple
  #   - 4
  #   - 4
  # - !!python/tuple
  #   - 4
  #   - 5
  # - !!python/tuple
  #   - 4
  #   - 6
  # - !!python/tuple
  #   - 5
  #   - 3
  # - !!python/tuple
  #   - 5
  #   - 4
  # - !!python/tuple
  #   - 5
  #   - 5
  # - !!python/tuple
  #   - 5
  #   - 6
  # - !!python/tuple
  #   - 6
  #   - 3
  # - !!python/tuple
  #   - 6
  #   - 4
  # - !!python/tuple
  #   - 6
  #   - 5
  # - !!python/tuple
  #   - 6
  #   - 6
  # - !!python/tuple
  #   - 7
  #   - 3
  # - !!python/tuple
  #   - 7
  #   - 4
  # - !!python/tuple
  #   - 7
  #   - 5
  # - !!python/tuple
  #   - 7
  #   - 6
  # - !!python/tuple
  #   - 8
  #   - 3
  # - !!python/tuple
  #   - 8
  #   - 4
  # - !!python/tuple
  #   - 8
  #   - 5
  # - !!python/tuple
  #   - 8
  #   - 6
  # - !!python/tuple
  #   - 9
  #   - 3
  # - !!python/tuple
  #   - 9
  #   - 4
  # - !!python/tuple
  #   - 9
  #   - 5
  # - !!python/tuple
  #   - 9
  #   - 6
  # - !!python/tuple
  #   - 10
  #   - 3
  # - !!python/tuple
  #   - 10
  #   - 4
  # - !!python/tuple
  #   - 10
  #   - 5
  # - !!python/tuple
  #   - 10
  #   - 6
  # - !!python/tuple
  #   - 11
  #   - 3
  # - !!python/tuple
  #   - 11
  #   - 4
  # - !!python/tuple
  #   - 11
  #   - 5
  # - !!python/tuple
  #   - 11
  #   - 6
  # - !!python/tuple
  #   - 12
  #   - 3
  # - !!python/tuple
  #   - 12
  #   - 4
  # - !!python/tuple
  #   - 12
  #   - 5
  # - !!python/tuple
  #   - 12
  #   - 6